#!/bin/bash
#PBS -N paradis_optuna_4gpu
#PBS -q gpu
#PBS -l select=1:ncpus=48:mpiprocs=4:ngpus=4:mem=436G
#PBS -l walltime=12:00:00
#PBS -j n
#PBS -o /space/hall5/sitestore/eccc/mrd/rpnatm/avg000/Toy_Dataset_Shallow_Water/swan/err_out/out/paradis_optuna_4gpu.out
#PBS -e /space/hall5/sitestore/eccc/mrd/rpnatm/avg000/Toy_Dataset_Shallow_Water/swan/err_out/err/paradis_optuna_4gpu.err

set -euo pipefail

REPO="/space/hall5/sitestore/eccc/mrd/rpnatm/avg000/Toy_Dataset_Shallow_Water/swan"
PY="/home/csu001/data/ppp5/conda_env/paradis/bin/python"

mkdir -p "$REPO/err_out/out" "$REPO/err_out/err"

cd "$REPO"

echo "HOST: $(hostname)"
echo "CWD:  $(pwd)"
echo "PY:   $PY"
echo "TIME: $(date)"
echo "GPU:"
nvidia-smi || true

# quick sanity
$PY -c "import torch; print('torch', torch.__version__, 'cuda?', torch.cuda.is_available())"
$PY -c "import optuna; print('optuna', optuna.__version__)"

# Optuna search:
# - dt_solver fixed to 30
$PY optuna_paradis_sweep_v1.py \
  --repo_dir "$REPO" \
  --python_bin "$PY" \
  --config "config_paradis.yaml" \
  --save_dir "trial_optuna" \
  --n_trials 20 \
  --n_jobs 4 \
  --study_name "paradis_dt30_train_ft_sweep" \
  --storage "sqlite:///trial/optuna_dt75_train_ft.db" \
  --seed 42
