#!/usr/bin/env python3
"""
Visualize LR/HR shallow-water rollout trajectories generated by generate_dataset.py.

Examples
--------
# Static figure: all rollout steps, field channel 0
python visualize_rollout.py \
    --data data/swe_paired.h5 \
    --ic 0 \
    --field 0 \
    --mode grid

# Animate channel 2 and write a GIF
python visualize_rollout.py \
    --data data/swe_paired.h5 \
    --ic 12 \
    --field 2 \
    --mode animation \
    --save-dir figures \
    --format gif

# Plot wind magnitude instead of a scalar field
python visualize_rollout.py \
    --data data/swe_paired.h5 \
    --ic 4 \
    --quantity wind_speed \
    --mode both \
    --save-dir figures
"""

from __future__ import annotations

import argparse
from pathlib import Path

import h5py
import matplotlib.animation as animation
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import Normalize, TwoSlopeNorm


FIELD_LABELS = {
    0: "Field channel 0",
    1: "Field channel 1",
    2: "Field channel 2",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualize LR/HR rollout trajectories from paired SWE HDF5 data."
    )
    parser.add_argument(
        "--data",
        type=Path,
        required=True,
        help="Path to the HDF5 dataset generated by generate_dataset.py.",
    )
    parser.add_argument(
        "--ic",
        type=int,
        required=True,
        help="Initial-condition index, zero-based.",
    )
    parser.add_argument(
        "--quantity",
        choices=["field", "wind_speed", "u", "v"],
        default="field",
        help="Quantity to plot. Default: field.",
    )
    parser.add_argument(
        "--field",
        type=int,
        choices=[0, 1, 2],
        default=0,
        help="Scalar-field channel when --quantity field. Default: 0.",
    )
    parser.add_argument(
        "--mode",
        choices=["grid", "animation", "both"],
        default="grid",
        help="Output type. Default: grid.",
    )
    parser.add_argument(
        "--save-dir",
        type=Path,
        default=Path("rollout_figures"),
        help="Directory for saved figures/animations.",
    )
    parser.add_argument(
        "--format",
        choices=["gif", "mp4"],
        default="gif",
        help="Animation format. MP4 requires ffmpeg. Default: gif.",
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=3,
        help="Frames per second for animation. Default: 3.",
    )
    parser.add_argument(
        "--cmap",
        default="RdBu_r",
        help="Matplotlib colormap for scalar fields. Default: RdBu_r.",
    )
    parser.add_argument(
        "--quiver-step",
        type=int,
        default=0,
        help=(
            "Overlay wind arrows every N grid points. "
            "Use 0 to disable quiver overlay. Default: 0."
        ),
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show figures interactively after writing them.",
    )
    return parser.parse_args()


def read_metadata(h5_path: Path, ic: int) -> tuple[dict, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    with h5py.File(h5_path, "r") as hf:
        required = ["lr/lrfields", "hr/hrfields", "lr/lrwinds", "hr/hrwinds"]
        missing = [key for key in required if key not in hf]
        if missing:
            raise KeyError(
                "This file does not contain full rollout trajectories. "
                f"Missing datasets: {missing}"
            )

        num_ics = hf["lr/lrfields"].shape[0]
        if not 0 <= ic < num_ics:
            raise IndexError(f"--ic must be in [0, {num_ics - 1}], got {ic}.")

        metadata = {key: hf.attrs[key] for key in hf.attrs.keys()}
        lr_fields = hf["lr/lrfields"][ic].astype(np.float32)
        hr_fields = hf["hr/hrfields"][ic].astype(np.float32)
        lr_winds = hf["lr/lrwinds"][ic].astype(np.float32)
        hr_winds = hf["hr/hrwinds"][ic].astype(np.float32)

    return metadata, lr_fields, hr_fields, lr_winds, hr_winds


def quantity_array(
    fields: np.ndarray,
    winds: np.ndarray,
    quantity: str,
    field_index: int,
) -> np.ndarray:
    if quantity == "field":
        return fields[:, field_index]

    if quantity == "wind_speed":
        return np.hypot(winds[:, 0], winds[:, 1])

    if quantity == "u":
        return winds[:, 0]

    if quantity == "v":
        return winds[:, 1]

    raise ValueError(f"Unsupported quantity: {quantity}")


def get_quantity_label(quantity: str, field_index: int) -> str:
    if quantity == "field":
        return FIELD_LABELS[field_index]
    if quantity == "wind_speed":
        return "Wind speed"
    return f"Wind component {quantity}"


def make_norm(data_lr: np.ndarray, data_hr: np.ndarray, quantity: str) -> Normalize:
    vmin = float(min(data_lr.min(), data_hr.min()))
    vmax = float(max(data_lr.max(), data_hr.max()))

    if np.isclose(vmin, vmax):
        delta = max(abs(vmin) * 1e-6, 1e-8)
        return Normalize(vmin=vmin - delta, vmax=vmax + delta)

    if quantity in {"field", "u", "v"} and vmin < 0.0 < vmax:
        vmax_abs = max(abs(vmin), abs(vmax))
        return TwoSlopeNorm(vmin=-vmax_abs, vcenter=0.0, vmax=vmax_abs)

    return Normalize(vmin=vmin, vmax=vmax)


def add_quiver(
    ax: plt.Axes,
    winds: np.ndarray,
    step: int,
    color: str = "black",
) -> None:
    if step <= 0:
        return

    _, nlat, nlon = winds.shape
    yy, xx = np.mgrid[0:nlat:step, 0:nlon:step]

    ax.quiver(
        xx,
        yy,
        winds[0, ::step, ::step],
        winds[1, ::step, ::step],
        color=color,
        alpha=0.75,
        scale=None,
        width=0.002,
    )


def plot_grid(
    lr_data: np.ndarray,
    hr_data: np.ndarray,
    lr_winds: np.ndarray,
    hr_winds: np.ndarray,
    norm: Normalize,
    label: str,
    ic: int,
    dt: float,
    cmap: str,
    quiver_step: int,
    out_path: Path,
) -> None:
    nframes = lr_data.shape[0]
    ncols = min(4, nframes)
    nrows = int(np.ceil(nframes / ncols))

    fig, axes = plt.subplots(
        nrows=nrows * 2,
        ncols=ncols,
        figsize=(4.0 * ncols, 3.35 * nrows * 2),
        constrained_layout=True,
        squeeze=False,
    )

    image = None

    for t in range(nframes):
        row = (t // ncols) * 2
        col = t % ncols
        time = t * dt

        ax_lr = axes[row, col]
        ax_hr = axes[row + 1, col]

        image = ax_lr.imshow(
            lr_data[t],
            origin="lower",
            cmap=cmap,
            norm=norm,
            aspect="auto",
        )
        ax_hr.imshow(
            hr_data[t],
            origin="lower",
            cmap=cmap,
            norm=norm,
            aspect="auto",
        )

        add_quiver(ax_lr, lr_winds[t], quiver_step)
        add_quiver(ax_hr, hr_winds[t], quiver_step)

        ax_lr.set_title(f"LR | step {t} | t = {time:g}")
        ax_hr.set_title(f"HR | step {t} | t = {time:g}")

        for ax in (ax_lr, ax_hr):
            ax.set_xlabel("Longitude index")
            ax.set_ylabel("Latitude index")

    for t in range(nframes, nrows * ncols):
        row = (t // ncols) * 2
        col = t % ncols
        axes[row, col].set_visible(False)
        axes[row + 1, col].set_visible(False)

    fig.suptitle(
        f"IC {ic}: LR/HR rollout — {label}",
        fontsize=16,
        fontweight="bold",
    )
    fig.colorbar(image, ax=axes.ravel().tolist(), shrink=0.78, label=label)
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def plot_animation(
    lr_data: np.ndarray,
    hr_data: np.ndarray,
    lr_winds: np.ndarray,
    hr_winds: np.ndarray,
    norm: Normalize,
    label: str,
    ic: int,
    dt: float,
    cmap: str,
    quiver_step: int,
    out_path: Path,
    fps: int,
) -> None:
    nframes = lr_data.shape[0]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5), constrained_layout=True)
    ax_lr, ax_hr = axes

    im_lr = ax_lr.imshow(
        lr_data[0],
        origin="lower",
        cmap=cmap,
        norm=norm,
        aspect="auto",
    )
    im_hr = ax_hr.imshow(
        hr_data[0],
        origin="lower",
        cmap=cmap,
        norm=norm,
        aspect="auto",
    )

    q_lr = None
    q_hr = None

    for ax, title in zip(axes, ["Low resolution", "High resolution"]):
        ax.set_title(title)
        ax.set_xlabel("Longitude index")
        ax.set_ylabel("Latitude index")

    fig.colorbar(im_hr, ax=axes, shrink=0.9, label=label)
    title = fig.suptitle("", fontsize=15, fontweight="bold")

    def update(frame: int):
        nonlocal q_lr, q_hr

        im_lr.set_data(lr_data[frame])
        im_hr.set_data(hr_data[frame])

        if q_lr is not None:
            q_lr.remove()
            q_hr.remove()

        if quiver_step > 0:
            nlat_lr, nlon_lr = lr_data.shape[-2:]
            nlat_hr, nlon_hr = hr_data.shape[-2:]

            y_lr, x_lr = np.mgrid[0:nlat_lr:quiver_step, 0:nlon_lr:quiver_step]
            y_hr, x_hr = np.mgrid[0:nlat_hr:quiver_step, 0:nlon_hr:quiver_step]

            q_lr = ax_lr.quiver(
                x_lr,
                y_lr,
                lr_winds[frame, 0, ::quiver_step, ::quiver_step],
                lr_winds[frame, 1, ::quiver_step, ::quiver_step],
                color="black",
                alpha=0.75,
                scale=None,
                width=0.002,
            )
            q_hr = ax_hr.quiver(
                x_hr,
                y_hr,
                hr_winds[frame, 0, ::quiver_step, ::quiver_step],
                hr_winds[frame, 1, ::quiver_step, ::quiver_step],
                color="black",
                alpha=0.75,
                scale=None,
                width=0.002,
            )

        title.set_text(
            f"IC {ic}: {label} | rollout step {frame}/{nframes - 1} "
            f"| t = {frame * dt:g}"
        )

        return [im_lr, im_hr, title]

    ani = animation.FuncAnimation(
        fig,
        update,
        frames=nframes,
        interval=1000 / fps,
        blit=False,
        repeat=True,
    )

    if out_path.suffix == ".gif":
        writer = animation.PillowWriter(fps=fps)
    elif out_path.suffix == ".mp4":
        writer = animation.FFMpegWriter(fps=fps, bitrate=2500)
    else:
        raise ValueError(f"Unsupported animation extension: {out_path.suffix}")

    ani.save(out_path, writer=writer, dpi=150)
    plt.close(fig)


def main() -> None:
    args = parse_args()

    if not args.data.exists():
        raise FileNotFoundError(f"Dataset not found: {args.data}")

    metadata, lr_fields, hr_fields, lr_winds, hr_winds = read_metadata(
        args.data,
        args.ic,
    )

    lr_data = quantity_array(
        lr_fields,
        lr_winds,
        args.quantity,
        args.field,
    )
    hr_data = quantity_array(
        hr_fields,
        hr_winds,
        args.quantity,
        args.field,
    )

    if lr_data.shape[0] != hr_data.shape[0]:
        raise RuntimeError(
            f"LR and HR trajectory lengths differ: {lr_data.shape[0]} vs {hr_data.shape[0]}"
        )

    dt = float(metadata.get("dt", 1.0))
    norm = make_norm(lr_data, hr_data, args.quantity)
    label = get_quantity_label(args.quantity, args.field)

    args.save_dir.mkdir(parents=True, exist_ok=True)

    base = (
        f"ic_{args.ic:05d}_"
        f"{args.quantity}"
        f"{args.field if args.quantity == 'field' else ''}"
    )

    print("Dataset metadata:")
    print(f"  IC index:        {args.ic}")
    print(f"  IC type:         {metadata.get('ictype', 'unknown')}")
    print(f"  dt:              {dt}")
    print(f"  Rollout frames:  {lr_data.shape[0]}")
    print(f"  LR shape:        {lr_data.shape[1:]}")
    print(f"  HR shape:        {hr_data.shape[1:]}")
    print(f"  Quantity:        {label}")

    if args.mode in {"grid", "both"}:
        grid_path = args.save_dir / f"{base}_grid.png"
        plot_grid(
            lr_data=lr_data,
            hr_data=hr_data,
            lr_winds=lr_winds,
            hr_winds=hr_winds,
            norm=norm,
            label=label,
            ic=args.ic,
            dt=dt,
            cmap=args.cmap,
            quiver_step=args.quiver_step,
            out_path=grid_path,
        )
        print(f"Saved grid figure: {grid_path}")

    if args.mode in {"animation", "both"}:
        animation_path = args.save_dir / f"{base}.{args.format}"
        plot_animation(
            lr_data=lr_data,
            hr_data=hr_data,
            lr_winds=lr_winds,
            hr_winds=hr_winds,
            norm=norm,
            label=label,
            ic=args.ic,
            dt=dt,
            cmap=args.cmap,
            quiver_step=args.quiver_step,
            out_path=animation_path,
            fps=args.fps,
        )
        print(f"Saved animation: {animation_path}")

    if args.show:
        plt.show()


if __name__ == "__main__":
    main()